// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext{
        compile_sdk_version = 35
        build_tool_version = '34.0.0'
        kotlin_version = '2.1.0'
        ksp_version = "1.0.29"
        agp_version = '8.8.0'
        media3_version = "1.5.1"
        splitties_version = '3.0.0'
        room_version = '2.6.1'
    }
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://repo.huaweicloud.com/repository/maven/' }
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$kotlin_version-$ksp_version"
        classpath "com.google.gms:google-services:4.4.2"
        classpath "androidx.room:room-gradle-plugin:$room_version"
        classpath "de.undercouch:gradle-download-task:5.6.0"
    }
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
