plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlin.parcelize
    alias libs.plugins.room
    alias libs.plugins.ksp
    alias libs.plugins.google.services
}
apply from: 'download.gradle'

static def releaseTime() {
    return new Date().format("yy.MMddHH", TimeZone.getTimeZone("GMT+8"))
}

def name = "legado"
def version = "3." + releaseTime()
def gitCommits = Integer.parseInt('git rev-list HEAD --count'.execute().text.trim())

android {
    compileSdk = compile_sdk_version
    namespace 'io.legado.app'
    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    signingConfigs {
        if (project.hasProperty("RELEASE_STORE_FILE")) {
            myConfig {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
                v1SigningEnabled true
                v2SigningEnabled true
                enableV3Signing = true
                enableV4Signing = true
            }
        }
    }
    defaultConfig {
        applicationId "io.legado.app"
        minSdk 21
        targetSdk 35
        versionCode 10000 + gitCommits
        versionName version
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        project.ext.set("archivesBaseName", name + "_" + version)

        buildConfigField "String", "Cronet_Version", "\"$CronetVersion\""
        buildConfigField "String", "Cronet_Main_Version", "\"$CronetMainVersion\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += [
                        "room.incremental"     : "true",
                        "room.expandProjection": "true",
                        "room.schemaLocation"  : "$projectDir/schemas".toString()
                ]
            }
        }
    }
    buildFeatures {
        buildConfig true
        viewBinding true
    }
    buildTypes {
        release {
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                signingConfig signingConfigs.myConfig
            }
            applicationIdSuffix '.release'
            if (getApplicationIdSuffix() == '.releaseA') {
                manifestPlaceholders.put("app_name", "@string/app_name_a")
            }else {
                manifestPlaceholders.put("app_name", "@string/app_name")
            }

            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'cronet-proguard-rules.pro'
        }
        debug {
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                signingConfig signingConfigs.myConfig
            }
            manifestPlaceholders.put("app_name", "@string/app_name")

            applicationIdSuffix '.debug'
            versionNameSuffix 'debug'
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro', 'cronet-proguard-rules.pro'
        }
    }
    //noinspection GrDeprecatedAPIUsage
    flavorDimensions = ['mode']
    productFlavors {
        app {
            dimension "mode"
            manifestPlaceholders.put("APP_CHANNEL_VALUE", "app")
        }
        google {
            dimension "mode"
            manifestPlaceholders.put("APP_CHANNEL_VALUE", "google")
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //kotlin
    implementation libs.kotlin.stdlib
    implementation libs.kotlin.reflect

    //androidx
    implementation libs.androidx.core.core
    implementation libs.androidx.appcompat.appcompat
    implementation libs.androidx.activity.activity
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.fragment.fragment
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.recyclerview
    implementation libs.androidx.viewpager2
    implementation libs.androidx.webkit
    implementation libs.material

    //jetpack
    implementation libs.lifecycle.common.java8
    implementation libs.lifecycle.service
    implementation libs.room.runtime
    implementation libs.room.ktx
    ksp libs.room.compiler

    //google
    implementation libs.flexbox
    implementation libs.gson
    implementation libs.json.path
    implementation libs.okhttp
    implementation libs.protobuf.javalite
    implementation libs.glide.glide
    ksp libs.glide.compiler
    implementation libs.glide.okhttp
    implementation libs.glide.recyclerview
    implementation libs.glide.compose
    implementation libs.glide.ksp
    implementation libs.glide.avif
    implementation libs.avif
    implementation libs.glide.svg
    implementation libs.androidsvg

    //other
    implementation libs.commons.text
    implementation libs.jsoup
    implementation libs.jsoupxpath
    implementation libs.hutool.crypto
    implementation libs.quick.chinese.transfer.core
    implementation libs.colorpicker
    implementation libs.zxing.lite
    implementation libs.markwon.core
    implementation libs.markwon.image.glide
    implementation libs.markwon.ext.tables
    implementation libs.markwon.html
    implementation libs.nanohttpd.nanohttpd
    implementation libs.nanohttpd.websocket
    implementation libs.splitties.appctx
    implementation libs.splitties.activities
    implementation libs.splitties.systemservices
    implementation libs.splitties.view
    implementation libs.mozilla.rhino
    implementation libs.coroutines.core
    implementation libs.coroutines.android
    implementation libs.liveeventbus
    implementation libs.libarchive
    implementation libs.media.media
    implementation libs.media3.datasource.okhttp
    implementation libs.media3.exoplayer
    implementation libs.media3.session
    implementation libs.desugar

    //firebase
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.perf

    //test
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.runner
    androidTestImplementation libs.fragment.testing
}
